language: go
go:
  - 1.5
before_install:
  - go get github.com/xeipuuv/gojsonreference
  - go get github.com/xeipuuv/gojsonpointer
  - go get github.com/stretchr/testify/assert
  - go get go.mongodb.org/mongo-driver/bson
